#!/bin/bash
#
# copy EXIF data from an CR2 raw file to a JPG file (derived from it
#
usage(){
    echo usage: $0 exifsrc imgfile
    echo 
    echo copy EXIF data from exifsrc to imgfile
    exit 1
}

if [ $# -lt 2 ] ; then
    usage
    exit 2
fi

FROM=$1
TO=$2

if [ ! -f "${FROM}" ]
then
    echo source file not found
    abort
fi
if [ ! -f "${TO}" ]
then
    echo target file not found
    abort
fi
exiftool -tagsFromFile "${FROM}" \
	 -model                  \
	 -Lensmodel              \
	 -Exposuretime           \
	 -Fnumber                \
	 -ISO                    \
	 -Focallength            \
	 "${TO}"

# END
