#!/bin/bash
#
# create links in $MYBIN (see below, should be on $PATH)
# to make scripts easily accessible
#
WD="$(pwd)"
MYBIN=~/bin
if [ ! -d ${MYBIN} ] ; then
    mkdir ${MYBIN}
fi

for script in annotwexif cpexif mainexif exifwf
do
    echo ${script}
    if [ -f  ${MYBIN}/${script} ]
    then
	if [ ${MYBIN}/${script} -ot ${script} ]
	then
	    rm ${MYBIN}/${script}
	    cp "${script}" ${MYBIN}
	else
	    echo -e "\tup-to date"
	fi
    else
	cp "${script}" ${MYBIN}
    fi
done
# END
